import type { SeedQuestion } from "../types";

export const seedQuestions: SeedQuestion[] = [

  // ─── WEATHER ─────────────────────────────────────────────────────────────
  {
    sourceRef: "wx-vfr-cloud-clearance-class-e-below-10k",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "What minimum cloud clearance is required for VFR flight in controlled airspace (Class E) below 10,000 feet MSL during daytime?",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "500 feet below, 1,000 feet above, and 2,000 feet horizontal", isCorrect: true },
      { label: "B", text: "500 feet above, 1,000 feet below, and 2,000 feet horizontal", isCorrect: false },
      { label: "C", text: "Clear of clouds", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-metar-ovc-ceiling",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "In a METAR report, the sky condition 'OVC008' means:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Overcast ceiling at 800 feet AGL", isCorrect: true },
      { label: "B", text: "Overcast clouds at 8,000 feet MSL", isCorrect: false },
      { label: "C", text: "Scattered clouds at 800 feet AGL", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-taf-validity",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "A Terminal Aerodrome Forecast (TAF) is typically valid for:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "6 hours", isCorrect: false },
      { label: "B", text: "12 hours, with some issued for 30 hours", isCorrect: false },
      { label: "C", text: "24 hours, with some issued for 30 hours", isCorrect: true },
    ],
  },
  {
    sourceRef: "wx-density-altitude-high",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "Which conditions result in the highest density altitude?",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "High elevation, high temperature, and high humidity", isCorrect: true },
      { label: "B", text: "Low elevation, low temperature, and low humidity", isCorrect: false },
      { label: "C", text: "High elevation, low temperature, and high humidity", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-thunderstorm-avoidance",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "What is the recommended minimum distance to fly around a severe thunderstorm?",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "5 nautical miles", isCorrect: false },
      { label: "B", text: "10 nautical miles", isCorrect: false },
      { label: "C", text: "20 nautical miles", isCorrect: true },
    ],
  },
  {
    sourceRef: "wx-wind-shear",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "Low-level wind shear is most hazardous to aircraft because it can cause:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Sudden, unexpected airspeed and altitude changes near the ground", isCorrect: true },
      { label: "B", text: "Gradual loss of lift at cruise altitude", isCorrect: false },
      { label: "C", text: "Excessive fuel burn during climb", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-dew-point-spread",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "When the temperature-dew point spread is 2°C or less and decreasing, a pilot should expect:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Freezing rain", isCorrect: false },
      { label: "B", text: "Fog or low clouds forming", isCorrect: true },
      { label: "C", text: "Severe turbulence", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-structural-icing",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "Structural icing on an aircraft is most likely to form when:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Flying through visible moisture with temperatures at or below 0°C", isCorrect: true },
      { label: "B", text: "Flying in clear air at high altitude", isCorrect: false },
      { label: "C", text: "Flying in dry snow above 10,000 feet", isCorrect: false },
    ],
  },

  // ─── REGULATIONS ─────────────────────────────────────────────────────────
  {
    sourceRef: "reg-required-docs-arrow",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "Which documents must be aboard an aircraft during flight?",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "Airworthiness certificate, registration, and a maintenance logbook", isCorrect: false },
      { label: "B", text: "Airworthiness certificate, registration, operating limitations, and weight and balance data", isCorrect: true },
      { label: "C", text: "Registration, radio station license, and a list of required equipment", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-flight-review",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "To act as pilot in command, a private pilot must have completed a flight review within the preceding:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "12 calendar months", isCorrect: false },
      { label: "B", text: "24 calendar months", isCorrect: true },
      { label: "C", text: "36 calendar months", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-passenger-currency",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "To carry passengers at night, a pilot must have made at least three takeoffs and landings to a full stop at night within the preceding:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "30 days", isCorrect: false },
      { label: "B", text: "60 days", isCorrect: false },
      { label: "C", text: "90 days", isCorrect: true },
    ],
  },
  {
    sourceRef: "reg-alcohol-drugs",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "Under 14 CFR Part 91, no person may act as a crewmember within how many hours after consuming alcohol?",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "4 hours", isCorrect: false },
      { label: "B", text: "8 hours", isCorrect: true },
      { label: "C", text: "12 hours", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-speed-limit-below-10k",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "What is the maximum indicated airspeed permitted below 10,000 feet MSL?",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "200 knots", isCorrect: false },
      { label: "B", text: "250 knots", isCorrect: true },
      { label: "C", text: "300 knots", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-medical-third-class",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "A third-class medical certificate issued to a pilot who is 40 years of age is valid for private pilot operations for:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "12 calendar months", isCorrect: false },
      { label: "B", text: "24 calendar months", isCorrect: true },
      { label: "C", text: "60 calendar months", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-right-of-way-converging",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "When two aircraft are converging at approximately the same altitude, which aircraft has the right of way?",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "The aircraft on the left", isCorrect: false },
      { label: "B", text: "The aircraft on the right", isCorrect: true },
      { label: "C", text: "The faster aircraft", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-vfr-fuel-requirements-day",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "For VFR flight during the day, a pilot must carry enough fuel to fly to the first point of intended landing and then for at least:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "20 minutes at normal cruise speed", isCorrect: false },
      { label: "B", text: "30 minutes at normal cruise speed", isCorrect: true },
      { label: "C", text: "45 minutes at normal cruise speed", isCorrect: false },
    ],
  },

  // ─── NAVIGATION ──────────────────────────────────────────────────────────
  {
    sourceRef: "nav-vot-check",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "While checking a VOR receiver with a VOT, the CDI centers. The OBS and TO/FROM indicator should read:",
    acsCode: "PA.VI.B",
    options: [
      { label: "A", text: "0° TO or 180° FROM", isCorrect: false },
      { label: "B", text: "0° FROM or 180° TO", isCorrect: true },
      { label: "C", text: "360° TO only", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-magnetic-variation-west",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "If the true course is 090° and the magnetic variation is 10° West, the magnetic course is:",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "080°", isCorrect: false },
      { label: "B", text: "090°", isCorrect: false },
      { label: "C", text: "100°", isCorrect: true },
    ],
  },
  {
    sourceRef: "nav-sectional-magenta-airport",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "On a sectional aeronautical chart, a magenta circle around an airport symbol indicates:",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "The airport has a control tower", isCorrect: false },
      { label: "B", text: "Class D airspace surrounds the airport", isCorrect: false },
      { label: "C", text: "Class E airspace begins at the surface", isCorrect: true },
    ],
  },
  {
    sourceRef: "nav-vor-radial-definition",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "A VOR radial is defined as:",
    acsCode: "PA.VI.B",
    options: [
      { label: "A", text: "A magnetic bearing TO the VOR station", isCorrect: false },
      { label: "B", text: "A magnetic bearing FROM the VOR station", isCorrect: true },
      { label: "C", text: "A true bearing FROM the VOR station", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-time-speed-distance",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "An aircraft travels 150 nautical miles in 1 hour 15 minutes. What is its groundspeed?",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "100 knots", isCorrect: false },
      { label: "B", text: "120 knots", isCorrect: true },
      { label: "C", text: "150 knots", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-sectional-scale",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "Sectional aeronautical charts are published at a scale of:",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "1:250,000", isCorrect: false },
      { label: "B", text: "1:500,000", isCorrect: true },
      { label: "C", text: "1:1,000,000", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-course-deviation-indicator",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "When flying FROM a VOR and the CDI needle deflects to the LEFT, the aircraft is:",
    acsCode: "PA.VI.B",
    options: [
      { label: "A", text: "Left of the selected radial", isCorrect: false },
      { label: "B", text: "Right of the selected radial", isCorrect: true },
      { label: "C", text: "On the selected radial but heading away from the station", isCorrect: false },
    ],
  },

  // ─── AERODYNAMICS ─────────────────────────────────────────────────────────
  {
    sourceRef: "aero-load-factor-turn",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "As bank angle increases in a constant-altitude turn, the load factor and the stall speed will:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Both increase", isCorrect: true },
      { label: "B", text: "Both decrease", isCorrect: false },
      { label: "C", text: "Load factor increases while stall speed remains constant", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-angle-of-attack-stall",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "An aircraft will always stall at the same:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Airspeed, regardless of attitude", isCorrect: false },
      { label: "B", text: "Critical angle of attack, regardless of airspeed or attitude", isCorrect: true },
      { label: "C", text: "Altitude and airspeed combination", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-ground-effect",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Ground effect is most significant when an aircraft is flying at an altitude of:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "One wingspan or less above the ground", isCorrect: true },
      { label: "B", text: "Two wingspans above the ground", isCorrect: false },
      { label: "C", text: "500 feet AGL", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-wake-turbulence",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Wake turbulence vortices from a large aircraft are most hazardous when that aircraft is:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Heavy, slow, and in landing configuration with gear and flaps down", isCorrect: true },
      { label: "B", text: "Light, fast, and in cruise configuration", isCorrect: false },
      { label: "C", text: "Heavy and at high speed in clean configuration", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-p-factor",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "P-factor (asymmetric propeller thrust) tends to yaw a single-engine airplane with a clockwise-rotating propeller (as seen from the cockpit) to the:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Right, especially at high angles of attack and low airspeeds", isCorrect: false },
      { label: "B", text: "Left, especially at high angles of attack and low airspeeds", isCorrect: true },
      { label: "C", text: "Left during cruise, right during climb", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-flap-effect-lift-drag",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Extending flaps increases:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Lift only", isCorrect: false },
      { label: "B", text: "Drag only", isCorrect: false },
      { label: "C", text: "Both lift and drag", isCorrect: true },
    ],
  },
  {
    sourceRef: "aero-bernoulli-lift",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "According to Bernoulli's principle, as the velocity of air over the top of an airfoil increases, the pressure:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Increases, creating lift", isCorrect: false },
      { label: "B", text: "Decreases, creating lift", isCorrect: true },
      { label: "C", text: "Remains constant regardless of velocity", isCorrect: false },
    ],
  },

  // ─── AIRSPACE ─────────────────────────────────────────────────────────────
  {
    sourceRef: "airspace-class-b-requirements",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "To operate within Class B airspace, a pilot must have at minimum a:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "Student pilot certificate with an instructor endorsement", isCorrect: false },
      { label: "B", text: "Private pilot certificate", isCorrect: true },
      { label: "C", text: "Instrument rating", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-class-b-equipment",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "To fly in Class B airspace, an aircraft must be equipped with:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "A transponder with Mode C and ADS-B Out", isCorrect: true },
      { label: "B", text: "Only a Mode C transponder", isCorrect: false },
      { label: "C", text: "Two-way radio communication equipment only", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-class-c-requirements",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "What are the minimum requirements to operate within Class C airspace?",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "ATC clearance, two-way radio, and Mode C transponder", isCorrect: false },
      { label: "B", text: "Two-way radio communication and Mode C transponder (ATC clearance not required)", isCorrect: false },
      { label: "C", text: "Two-way radio communication established with ATC, and a Mode C transponder", isCorrect: true },
    ],
  },
  {
    sourceRef: "airspace-class-d-ceiling",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "Class D airspace typically extends from the surface to:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "2,500 feet AGL", isCorrect: false },
      { label: "B", text: "2,500 to 3,000 feet AGL (shown on charts as MSL altitude)", isCorrect: true },
      { label: "C", text: "10,000 feet MSL", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-class-g-uncontrolled",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "What are the VFR visibility and cloud clearance requirements in Class G airspace below 1,200 feet AGL during the day?",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "1 statute mile visibility, clear of clouds", isCorrect: true },
      { label: "B", text: "3 statute miles, 500 below / 1,000 above / 2,000 horizontal", isCorrect: false },
      { label: "C", text: "3 statute miles, clear of clouds", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-prohibited-restricted",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "Flight in a restricted area is:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "Never permitted under any circumstances", isCorrect: false },
      { label: "B", text: "Permitted when the controlling agency authorizes entry", isCorrect: true },
      { label: "C", text: "Permitted for VFR flight without prior permission", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-mode-c-veil",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "A Mode C transponder and ADS-B Out are required within the Mode C veil, which extends how far from the primary airport of Class B airspace?",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "10 nautical miles", isCorrect: false },
      { label: "B", text: "30 nautical miles", isCorrect: true },
      { label: "C", text: "60 nautical miles", isCorrect: false },
    ],
  },

  // ─── AIRPORT OPERATIONS ──────────────────────────────────────────────────
  {
    sourceRef: "airport-traffic-pattern-altitude",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "The standard traffic pattern altitude for propeller-driven aircraft at airports without a published traffic pattern altitude is:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "500 feet AGL", isCorrect: false },
      { label: "B", text: "1,000 feet AGL", isCorrect: true },
      { label: "C", text: "1,500 feet AGL", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-rotating-beacon-day",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "When a rotating beacon operates during daylight hours at an airport in Class D airspace, it indicates:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "The airport is closed to all traffic", isCorrect: false },
      { label: "B", text: "The weather conditions are below VFR minimums (IFR conditions)", isCorrect: true },
      { label: "C", text: "Special VFR is in effect at that airport", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-runway-hold-short-sign",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "A runway hold short position sign has:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "White text on a red background", isCorrect: true },
      { label: "B", text: "Black text on a yellow background", isCorrect: false },
      { label: "C", text: "White text on a black background", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-papi-indication",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "When using a 4-light PAPI (Precision Approach Path Indicator), two white lights and two red lights indicate the aircraft is:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Above the glidepath", isCorrect: false },
      { label: "B", text: "On the correct glidepath", isCorrect: true },
      { label: "C", text: "Below the glidepath", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-light-gun-signals",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "A steady GREEN light gun signal directed at an aircraft on the ground means:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Cleared for takeoff", isCorrect: true },
      { label: "B", text: "Cleared to land", isCorrect: false },
      { label: "C", text: "Exercise extreme caution", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-traffic-pattern-direction",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "The standard direction of turns in an airport traffic pattern is:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Right turns", isCorrect: false },
      { label: "B", text: "Left turns", isCorrect: true },
      { label: "C", text: "Either left or right, pilot's discretion", isCorrect: false },
    ],
  },

  // ─── AIRCRAFT SYSTEMS ─────────────────────────────────────────────────────
  {
    sourceRef: "sys-carburetor-ice-conditions",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "Carburetor icing is most likely to form when the outside air temperature is:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Below -20°C", isCorrect: false },
      { label: "B", text: "Between -10°C and 21°C (14°F to 70°F) with high humidity", isCorrect: true },
      { label: "C", text: "Above 30°C in dry air", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-carb-heat-effect",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "When carburetor heat is applied to an engine with no carburetor ice present, engine RPM will:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Increase due to improved fuel vaporization", isCorrect: false },
      { label: "B", text: "Decrease slightly due to less dense air entering the carburetor", isCorrect: true },
      { label: "C", text: "Remain unchanged", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-fuel-grades-avgas",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "100LL aviation fuel is identified by its color of:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Red", isCorrect: false },
      { label: "B", text: "Blue", isCorrect: true },
      { label: "C", text: "Green", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-pitot-blockage",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "If the pitot tube becomes blocked by ice but the drain hole remains open, the airspeed indicator will:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Read high and continue to increase", isCorrect: false },
      { label: "B", text: "Read zero", isCorrect: true },
      { label: "C", text: "Act as an altimeter, showing altitude changes", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-gyro-instruments-vacuum",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "Which flight instruments are typically driven by the vacuum system?",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Airspeed indicator and altimeter", isCorrect: false },
      { label: "B", text: "Attitude indicator and heading indicator", isCorrect: true },
      { label: "C", text: "Turn coordinator and VSI", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-alternate-static-source",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "When the alternate static source is selected in an unpressurized aircraft, the altimeter will typically indicate:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Lower than actual altitude", isCorrect: false },
      { label: "B", text: "Correct altitude, no change", isCorrect: false },
      { label: "C", text: "Slightly higher than actual altitude", isCorrect: true },
    ],
  },
  {
    sourceRef: "sys-magneto-check-rpm-drop",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "During the pre-takeoff engine runup, an excessively large RPM drop on one magneto indicates:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "A fouled spark plug or faulty magneto", isCorrect: true },
      { label: "B", text: "The magneto switch is working correctly", isCorrect: false },
      { label: "C", text: "Carburetor icing is present", isCorrect: false },
    ],
  },

  // ─── WEIGHT & BALANCE ─────────────────────────────────────────────────────
  {
    sourceRef: "wb-cg-definition",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "The center of gravity (CG) of an aircraft is:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The point at which the aircraft would balance if suspended", isCorrect: true },
      { label: "B", text: "Always located at the wing's center of pressure", isCorrect: false },
      { label: "C", text: "The geometric center of the fuselage", isCorrect: false },
    ],
  },
  {
    sourceRef: "wb-aft-cg-effect",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "An aft center of gravity beyond the aft CG limit causes the aircraft to be:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "More stable longitudinally and harder to stall", isCorrect: false },
      { label: "B", text: "Less stable and possibly unable to recover from a stall", isCorrect: true },
      { label: "C", text: "Harder to control in roll but unaffected in pitch", isCorrect: false },
    ],
  },
  {
    sourceRef: "wb-forward-cg-effect",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "A forward CG condition causes the aircraft to require:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "More back elevator pressure to maintain level flight, increasing drag and reducing range", isCorrect: true },
      { label: "B", text: "Less elevator input and reduces stall speed", isCorrect: false },
      { label: "C", text: "Increased aileron deflection for coordinated turns", isCorrect: false },
    ],
  },
  {
    sourceRef: "wb-moment-computation",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "To compute the moment of an item in weight and balance calculations:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Add the weight and arm together", isCorrect: false },
      { label: "B", text: "Multiply the weight (in pounds) by the arm (in inches)", isCorrect: true },
      { label: "C", text: "Divide the total weight by the total arm", isCorrect: false },
    ],
  },
  {
    sourceRef: "wb-max-gross-weight",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "If the computed weight of an aircraft exceeds the maximum gross weight limit:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Flight is permitted if the CG is within limits", isCorrect: false },
      { label: "B", text: "Flight is not permitted; weight must be reduced", isCorrect: true },
      { label: "C", text: "Short flights under 30 minutes are allowed at the pilot's discretion", isCorrect: false },
    ],
  },

  // ─── PERFORMANCE ──────────────────────────────────────────────────────────
  {
    sourceRef: "perf-pressure-altitude",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "Pressure altitude is defined as:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The actual altitude above sea level", isCorrect: false },
      { label: "B", text: "The altitude shown on the altimeter when set to 29.92 in Hg", isCorrect: true },
      { label: "C", text: "The altitude corrected for temperature", isCorrect: false },
    ],
  },
  {
    sourceRef: "perf-density-altitude-effect",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "A high density altitude affects aircraft performance by:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Reducing engine power, propeller thrust, and lift — requiring longer takeoff distances", isCorrect: true },
      { label: "B", text: "Increasing engine power output due to thinner air", isCorrect: false },
      { label: "C", text: "Reducing takeoff distance because the aircraft accelerates faster", isCorrect: false },
    ],
  },
  {
    sourceRef: "perf-vx-vy-difference",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "Vx (best angle of climb speed) is used to:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Achieve the greatest altitude gain in the shortest distance over the ground", isCorrect: true },
      { label: "B", text: "Achieve the greatest altitude gain in the shortest time", isCorrect: false },
      { label: "C", text: "Achieve maximum endurance in cruise", isCorrect: false },
    ],
  },
  {
    sourceRef: "perf-headwind-crosswind",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "The wind is reported as 270° at 20 knots. The runway in use is Runway 24 (240°). The crosswind component is approximately:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "10 knots", isCorrect: true },
      { label: "B", text: "17 knots", isCorrect: false },
      { label: "C", text: "20 knots", isCorrect: false },
    ],
  },
  {
    sourceRef: "perf-landing-distance-factors",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "Which factor will INCREASE landing distance the most?",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Tailwind instead of headwind", isCorrect: true },
      { label: "B", text: "Lower gross weight", isCorrect: false },
      { label: "C", text: "Lower density altitude", isCorrect: false },
    ],
  },

  // ─── EMERGENCY PROCEDURES ─────────────────────────────────────────────────
  {
    sourceRef: "emerg-engine-failure-best-glide",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "Immediately following an engine failure in flight, the first priority is to:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "Declare an emergency on 121.5 MHz", isCorrect: false },
      { label: "B", text: "Establish best glide speed and select a suitable landing area", isCorrect: true },
      { label: "C", text: "Attempt an engine restart immediately", isCorrect: false },
    ],
  },
  {
    sourceRef: "emerg-squawk-emergency",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "In an emergency situation when radio communication is not possible, a pilot should squawk:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "7600", isCorrect: false },
      { label: "B", text: "7700", isCorrect: true },
      { label: "C", text: "7500", isCorrect: false },
    ],
  },
  {
    sourceRef: "emerg-electrical-fire",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "If an electrical fire is suspected in flight, the recommended action is to:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "Open all vents and increase airspeed to blow out the fire", isCorrect: false },
      { label: "B", text: "Turn off the master switch and all unnecessary electrical equipment, then land as soon as possible", isCorrect: true },
      { label: "C", text: "Use the fire extinguisher immediately and continue to destination", isCorrect: false },
    ],
  },
  {
    sourceRef: "emerg-engine-fire-takeoff",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "If an engine fire develops on takeoff prior to liftoff, the pilot should:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "Continue the takeoff to gain altitude and then turn back", isCorrect: false },
      { label: "B", text: "Throttle back, apply brakes, and stop the aircraft on the remaining runway", isCorrect: true },
      { label: "C", text: "Apply full power to climb quickly above the fire", isCorrect: false },
    ],
  },
  {
    sourceRef: "emerg-forced-landing-site",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "When selecting a forced landing field, a pilot should consider all of the following EXCEPT:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "Wind direction and speed", isCorrect: false },
      { label: "B", text: "The proximity of the field to a highway for rescue access", isCorrect: true },
      { label: "C", text: "Field length and surface condition", isCorrect: false },
    ],
  },

  // ─── PREFLIGHT PLANNING ───────────────────────────────────────────────────
  {
    sourceRef: "preflight-weather-briefing-types",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "Which type of weather briefing should a pilot request when filing a flight plan and no prior information has been received?",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Abbreviated briefing", isCorrect: false },
      { label: "B", text: "Outlook briefing", isCorrect: false },
      { label: "C", text: "Standard briefing", isCorrect: true },
    ],
  },
  {
    sourceRef: "preflight-notam-types",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "A NOTAM (D) contains information about:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "Distant NOTAMs that affect navigation data", isCorrect: false },
      { label: "B", text: "Changes to airport facilities, procedures, and airspace not in the Chart Supplement", isCorrect: true },
      { label: "C", text: "Temporary flight restrictions only", isCorrect: false },
    ],
  },
  {
    sourceRef: "preflight-vfr-flight-plan",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "After filing a VFR flight plan, if the pilot has not arrived at the destination and has not closed the flight plan within how long after the ETA will search and rescue procedures be initiated?",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "30 minutes", isCorrect: true },
      { label: "B", text: "1 hour", isCorrect: false },
      { label: "C", text: "2 hours", isCorrect: false },
    ],
  },
  {
    sourceRef: "preflight-fuel-night-requirements",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "For VFR flight at night, FAA regulations require enough fuel to fly to the first point of intended landing and then for at least:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "30 minutes at normal cruise speed", isCorrect: false },
      { label: "B", text: "45 minutes at normal cruise speed", isCorrect: true },
      { label: "C", text: "60 minutes at normal cruise speed", isCorrect: false },
    ],
  },
  {
    sourceRef: "preflight-pirep-interpretation",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "A PIREP (pilot weather report) is most useful to a pilot because it provides:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Forecast weather conditions along the route", isCorrect: false },
      { label: "B", text: "Actual weather conditions at a specific location and altitude as reported by another pilot", isCorrect: true },
      { label: "C", text: "Official weather observation from a certified station", isCorrect: false },
    ],
  },

  // ─── NIGHT OPERATIONS ─────────────────────────────────────────────────────
  {
    sourceRef: "night-vision-dark-adaptation",
    chapterSlug: "night-operations",
    chapterTitle: "Night Operations",
    chapterOrder: 12,
    chapterDescription: "Night vision, lighting requirements, and special considerations.",
    stem: "To best preserve night vision when looking at a chart inside the cockpit, a pilot should use:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "A bright white flashlight", isCorrect: false },
      { label: "B", text: "A red-filtered flashlight", isCorrect: true },
      { label: "C", text: "A blue-filtered flashlight", isCorrect: false },
    ],
  },
  {
    sourceRef: "night-aircraft-lighting",
    chapterSlug: "night-operations",
    chapterTitle: "Night Operations",
    chapterOrder: 12,
    chapterDescription: "Night vision, lighting requirements, and special considerations.",
    stem: "The red navigation light on an aircraft is located on the:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Right (starboard) wingtip", isCorrect: false },
      { label: "B", text: "Left (port) wingtip", isCorrect: true },
      { label: "C", text: "Tail", isCorrect: false },
    ],
  },
  {
    sourceRef: "night-illusions-runway",
    chapterSlug: "night-operations",
    chapterTitle: "Night Operations",
    chapterOrder: 12,
    chapterDescription: "Night vision, lighting requirements, and special considerations.",
    stem: "A visual illusion at night that can cause a pilot to fly a dangerously low approach is:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Black hole approach (no visible horizon or ground references)", isCorrect: true },
      { label: "B", text: "A wide runway making the pilot feel too high", isCorrect: false },
      { label: "C", text: "An upsloping runway making the pilot feel too low", isCorrect: false },
    ],
  },

  // ─── WEATHER (batch 2) ────────────────────────────────────────────────────
  {
    sourceRef: "wx-cold-front-characteristics",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "Which weather conditions are typically associated with the passage of a cold front?",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Gradual clearing, rising temperatures, and decreasing winds", isCorrect: false },
      { label: "B", text: "Rapid clearing, dropping temperatures, and shifting winds to the northwest", isCorrect: true },
      { label: "C", text: "Steady rain lasting 24–48 hours with low stratus clouds", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-airmet-sierra",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "AIRMET Sierra is issued to warn pilots of:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Severe turbulence above 18,000 feet MSL", isCorrect: false },
      { label: "B", text: "IFR conditions and/or extensive mountain obscuration", isCorrect: true },
      { label: "C", text: "Icing conditions below the freezing level", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-microburst-characteristics",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "A microburst is most accurately described as:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "A small, intense downdraft that spreads outward as it reaches the ground, creating severe wind shear", isCorrect: true },
      { label: "B", text: "A rotating column of air extending from a cumulonimbus cloud to the ground", isCorrect: false },
      { label: "C", text: "A narrow band of fast-moving air at high altitude", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-sigmet-definition",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "A SIGMET (WS) advises of weather considered potentially hazardous to which aircraft?",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "VFR aircraft only", isCorrect: false },
      { label: "B", text: "IFR aircraft only", isCorrect: false },
      { label: "C", text: "All aircraft", isCorrect: true },
    ],
  },
  {
    sourceRef: "wx-mountain-wave-turbulence",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "Mountain wave turbulence is most likely to be encountered when wind crosses a mountain range at a speed of at least:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "15 knots perpendicular to the ridge", isCorrect: false },
      { label: "B", text: "25 knots or more and nearly perpendicular to the ridge", isCorrect: true },
      { label: "C", text: "40 knots at any angle to the ridge", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-winds-aloft-forecast",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "Winds aloft forecasts (FB) are not issued for altitudes within how many feet of the station elevation?",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "500 feet", isCorrect: false },
      { label: "B", text: "1,500 feet", isCorrect: true },
      { label: "C", text: "3,000 feet", isCorrect: false },
    ],
  },
  {
    sourceRef: "wx-warm-front-weather",
    chapterSlug: "weather",
    chapterTitle: "Weather",
    chapterOrder: 1,
    chapterDescription: "Weather theory, reports, forecasts, and VFR minimums.",
    stem: "Weather typically associated with a warm front includes:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Cumulonimbus clouds, heavy showers, and gusty winds", isCorrect: false },
      { label: "B", text: "Widespread stratus clouds, continuous rain or drizzle, and poor visibility", isCorrect: true },
      { label: "C", text: "Clear skies with rapidly decreasing temperatures", isCorrect: false },
    ],
  },

  // ─── REGULATIONS (batch 2) ────────────────────────────────────────────────
  {
    sourceRef: "reg-ntsb-immediate-notification",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "Under NTSB Part 830, the operator of an aircraft must immediately notify the NTSB when an aircraft accident occurs. An aircraft accident is defined as an occurrence in which:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "Any damage to the aircraft occurs, regardless of injury", isCorrect: false },
      { label: "B", text: "A person suffers death or serious injury, or the aircraft receives substantial damage", isCorrect: true },
      { label: "C", text: "The aircraft is destroyed or more than $50,000 in damage occurs", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-basicmed",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "Under BasicMed, a pilot may act as PIC of an aircraft with no more than:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "4 occupants at altitudes up to 14,000 feet MSL", isCorrect: false },
      { label: "B", text: "5 occupants (including the pilot) at altitudes up to 18,000 feet MSL at 250 knots or less", isCorrect: true },
      { label: "C", text: "6 occupants at any altitude with no airspeed restriction", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-vfr-cruising-altitude",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "On a magnetic course of 185°, flying VFR above 3,000 feet AGL, a pilot should cruise at:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "Odd thousands plus 500 feet (e.g., 3,500 feet)", isCorrect: false },
      { label: "B", text: "Even thousands plus 500 feet (e.g., 4,500 feet)", isCorrect: true },
      { label: "C", text: "Any altitude that provides terrain clearance", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-elt-requirement",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "An ELT (Emergency Locator Transmitter) is required on most U.S.-registered aircraft and must be inspected or replaced:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "Every 6 calendar months", isCorrect: false },
      { label: "B", text: "Every 12 calendar months, or when 50% of useful life is expired", isCorrect: true },
      { label: "C", text: "Every 24 calendar months or after any hard landing", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-vfr-visibility-class-e-night",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "What are the VFR visibility requirements for flight in Class E airspace at night, below 10,000 feet MSL?",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "1 statute mile", isCorrect: false },
      { label: "B", text: "3 statute miles", isCorrect: true },
      { label: "C", text: "5 statute miles", isCorrect: false },
    ],
  },
  {
    sourceRef: "reg-landing-lights-requirement",
    chapterSlug: "regulations",
    chapterTitle: "Regulations",
    chapterOrder: 2,
    chapterDescription: "14 CFR Parts 61 and 91 rules for pilots and aircraft.",
    stem: "Landing lights are required for aircraft operated for hire at night. For privately operated aircraft, landing lights are:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "Required at all times for flight below 1,000 feet AGL", isCorrect: false },
      { label: "B", text: "Not required but strongly recommended for collision avoidance", isCorrect: true },
      { label: "C", text: "Required only within Class B and Class C airspace", isCorrect: false },
    ],
  },

  // ─── NAVIGATION (batch 2) ─────────────────────────────────────────────────
  {
    sourceRef: "nav-compass-northerly-turning-error",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "When turning from a northerly heading to the east using a magnetic compass in the Northern Hemisphere, the compass will initially indicate:",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "A turn in the correct direction but overshoot east", isCorrect: false },
      { label: "B", text: "A turn toward the south (opposite direction)", isCorrect: true },
      { label: "C", text: "No movement until established on the easterly heading", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-compass-acceleration-error",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "On an easterly heading in the Northern Hemisphere, the magnetic compass will indicate a turn to the north when the aircraft:",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "Decelerates", isCorrect: false },
      { label: "B", text: "Accelerates", isCorrect: true },
      { label: "C", text: "Enters a bank", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-gps-raim",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "RAIM (Receiver Autonomous Integrity Monitoring) in a GPS receiver is important because it:",
    acsCode: "PA.VI.B",
    options: [
      { label: "A", text: "Increases the accuracy of GPS position fixes", isCorrect: false },
      { label: "B", text: "Warns the pilot when the GPS signal integrity is insufficient for safe navigation", isCorrect: true },
      { label: "C", text: "Allows GPS to operate without satellite contact", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-true-airspeed-calculation",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "As altitude increases, true airspeed (TAS) compared to indicated airspeed (IAS) at the same power setting will:",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "Decrease because the air is thinner", isCorrect: false },
      { label: "B", text: "Remain equal to indicated airspeed", isCorrect: false },
      { label: "C", text: "Increase because the air is less dense", isCorrect: true },
    ],
  },
  {
    sourceRef: "nav-chart-supplement",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "The Chart Supplement (formerly Airport/Facility Directory) is published every:",
    acsCode: "PA.VI.A",
    options: [
      { label: "A", text: "28 days", isCorrect: false },
      { label: "B", text: "56 days", isCorrect: true },
      { label: "C", text: "180 days", isCorrect: false },
    ],
  },
  {
    sourceRef: "nav-vor-service-volume",
    chapterSlug: "navigation",
    chapterTitle: "Navigation",
    chapterOrder: 3,
    chapterDescription: "VOR, GPS, charts, and dead reckoning.",
    stem: "A Terminal VOR (TVOR) is intended for use within a radius of approximately:",
    acsCode: "PA.VI.B",
    options: [
      { label: "A", text: "25 nautical miles", isCorrect: true },
      { label: "B", text: "40 nautical miles", isCorrect: false },
      { label: "C", text: "130 nautical miles", isCorrect: false },
    ],
  },

  // ─── AERODYNAMICS (batch 2) ───────────────────────────────────────────────
  {
    sourceRef: "aero-adverse-yaw",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Adverse yaw during a turn is caused by:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The downgoing aileron creating more drag than the upgoing aileron", isCorrect: true },
      { label: "B", text: "The upgoing aileron creating more drag than the downgoing aileron", isCorrect: false },
      { label: "C", text: "Engine torque opposing the direction of turn", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-vne-definition",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Vne (never-exceed speed) is shown on the airspeed indicator as:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The upper limit of the yellow arc", isCorrect: true },
      { label: "B", text: "The upper limit of the green arc", isCorrect: false },
      { label: "C", text: "A red radial line at the top of the white arc", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-va-maneuvering-speed",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Maneuvering speed (Va) is significant because below this speed:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The aircraft cannot exceed its design load factor with full deflection of a single control surface", isCorrect: true },
      { label: "B", text: "The aircraft is guaranteed to remain below its maximum structural cruising speed", isCorrect: false },
      { label: "C", text: "Flaps may be extended without risk of structural damage", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-spin-recovery",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "The standard spin recovery procedure for most single-engine aircraft (PARE) begins with:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Apply back elevator to increase angle of attack", isCorrect: false },
      { label: "B", text: "Power to idle and ailerons neutral", isCorrect: true },
      { label: "C", text: "Apply full aileron into the spin", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-torque-effect",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Engine torque reaction in a single-engine aircraft with a clockwise-rotating propeller (viewed from cockpit) tends to roll the aircraft to the:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Right", isCorrect: false },
      { label: "B", text: "Left", isCorrect: true },
      { label: "C", text: "Direction of the turn being made", isCorrect: false },
    ],
  },
  {
    sourceRef: "aero-induced-drag",
    chapterSlug: "aerodynamics",
    chapterTitle: "Aerodynamics",
    chapterOrder: 4,
    chapterDescription: "Forces of flight, stability, and aircraft performance limits.",
    stem: "Induced drag increases as:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Airspeed increases", isCorrect: false },
      { label: "B", text: "Angle of attack increases (airspeed decreases)", isCorrect: true },
      { label: "C", text: "Altitude increases at constant airspeed", isCorrect: false },
    ],
  },

  // ─── AIRSPACE (batch 2) ───────────────────────────────────────────────────
  {
    sourceRef: "airspace-tfr-types",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "A Temporary Flight Restriction (TFR) issued for a VIP movement under 14 CFR 91.141 typically prohibits flight within:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "3 nautical miles and 1,000 feet of the VIP movement", isCorrect: false },
      { label: "B", text: "3 nautical miles and 3,000 feet AGL within 30 nautical miles in some cases", isCorrect: false },
      { label: "C", text: "3 nautical miles and below 3,000 feet AGL of the movement", isCorrect: true },
    ],
  },
  {
    sourceRef: "airspace-military-training-routes",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "Military Training Routes (MTRs) with four-digit numbers (e.g., IR1234 or VR1234) are flown at altitudes:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "Above 1,500 feet AGL only", isCorrect: false },
      { label: "B", text: "At or below 1,500 feet AGL for at least part of the route", isCorrect: true },
      { label: "C", text: "Above 10,000 feet MSL", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-alert-area",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "An Alert Area is designated to advise pilots of:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "Areas where flight is prohibited without ATC clearance", isCorrect: false },
      { label: "B", text: "Areas with a high volume of pilot training or unusual aerial activity", isCorrect: true },
      { label: "C", text: "Areas reserved exclusively for military operations", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-class-a-requirements",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "Class A airspace in the contiguous U.S. extends from:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "10,000 feet MSL to 60,000 feet MSL", isCorrect: false },
      { label: "B", text: "18,000 feet MSL to FL600", isCorrect: true },
      { label: "C", text: "14,500 feet MSL to unlimited", isCorrect: false },
    ],
  },
  {
    sourceRef: "airspace-special-use-warning",
    chapterSlug: "airspace",
    chapterTitle: "Airspace",
    chapterOrder: 5,
    chapterDescription: "U.S. airspace classifications, requirements, and special use areas.",
    stem: "Flight through a Warning Area located beyond the 3 nautical mile limit from the U.S. coastline is:",
    acsCode: "PA.I.E",
    options: [
      { label: "A", text: "Prohibited for all civil aircraft", isCorrect: false },
      { label: "B", text: "Not prohibited but potentially hazardous due to military operations", isCorrect: true },
      { label: "C", text: "Allowed only with a clearance from the controlling agency", isCorrect: false },
    ],
  },

  // ─── AIRPORT OPERATIONS (batch 2) ────────────────────────────────────────
  {
    sourceRef: "airport-atis-information",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "ATIS (Automatic Terminal Information Service) is updated:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Every 30 minutes regardless of conditions", isCorrect: false },
      { label: "B", text: "When any official weather observation is received or when certain conditions change", isCorrect: true },
      { label: "C", text: "Only at the top of each hour", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-taxiway-markings-color",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "Taxiway centerline markings are:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "White solid lines", isCorrect: false },
      { label: "B", text: "Yellow solid lines", isCorrect: true },
      { label: "C", text: "Yellow dashed lines", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-runway-displaced-threshold",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "A displaced threshold on a runway means that the area before the threshold marking:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Cannot be used for any aircraft operations", isCorrect: false },
      { label: "B", text: "May be used for takeoff, rollout, and taxi — but not for landing", isCorrect: true },
      { label: "C", text: "Is closed and marked with X symbols", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-wake-turbulence-departure",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "When departing behind a large aircraft on the same runway, to avoid wake turbulence a pilot should:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Begin takeoff roll from the same point as the large aircraft and climb above its flight path", isCorrect: false },
      { label: "B", text: "Begin takeoff from a point beyond the large aircraft's rotation point and fly above its flight path", isCorrect: true },
      { label: "C", text: "Wait at least 5 minutes before beginning the takeoff roll", isCorrect: false },
    ],
  },
  {
    sourceRef: "airport-runway-incursion-hotspot",
    chapterSlug: "airport-operations",
    chapterTitle: "Airport Operations",
    chapterOrder: 6,
    chapterDescription: "Traffic patterns, airport lighting, signs, and surface operations.",
    stem: "Airport Hot Spots shown on airport diagrams indicate locations that:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Have a history of runway incursions or surface incidents", isCorrect: true },
      { label: "B", text: "Require special equipment or a high-performance endorsement", isCorrect: false },
      { label: "C", text: "Have overhead obstructions or unusual noise abatement procedures", isCorrect: false },
    ],
  },

  // ─── AIRCRAFT SYSTEMS (batch 2) ───────────────────────────────────────────
  {
    sourceRef: "sys-mixture-control-cruise",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "At cruise altitudes above 3,000 feet, leaning the mixture is recommended to:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Increase engine RPM and reduce fuel consumption", isCorrect: false },
      { label: "B", text: "Prevent spark plug fouling and restore engine efficiency lost due to thinner air", isCorrect: true },
      { label: "C", text: "Lower engine temperatures and prevent overheating", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-fuel-tank-sump-check",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "During preflight, fuel sumps should be drained and checked for:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Correct fuel quantity and appropriate fuel grade only", isCorrect: false },
      { label: "B", text: "Water, sediment, and correct fuel grade and color", isCorrect: true },
      { label: "C", text: "Fuel pressure and temperature only", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-oil-pressure-low",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "If the oil pressure gauge shows low or zero oil pressure in flight, a pilot should:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Reduce power and land as soon as possible to prevent engine damage", isCorrect: true },
      { label: "B", text: "Continue flight while monitoring oil temperature", isCorrect: false },
      { label: "C", text: "Add power to increase oil circulation", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-manifold-pressure",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "In a normally aspirated (non-turbocharged) engine at full throttle, as the aircraft climbs, manifold pressure will:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Remain constant because the throttle is at full open", isCorrect: false },
      { label: "B", text: "Increase due to ram air effect", isCorrect: false },
      { label: "C", text: "Decrease because ambient air pressure decreases with altitude", isCorrect: true },
    ],
  },
  {
    sourceRef: "sys-turn-coordinator-function",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "The ball (inclinometer) in the turn coordinator indicates:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The rate of turn in degrees per second", isCorrect: false },
      { label: "B", text: "Whether the turn is coordinated (ball centered = coordinated)", isCorrect: true },
      { label: "C", text: "The angle of bank directly", isCorrect: false },
    ],
  },
  {
    sourceRef: "sys-vsi-lag",
    chapterSlug: "aircraft-systems",
    chapterTitle: "Aircraft Systems",
    chapterOrder: 7,
    chapterDescription: "Engine, fuel, electrical, pitot-static, and flight instruments.",
    stem: "The vertical speed indicator (VSI) has a lag of approximately how many seconds before it stabilizes after a pitch change?",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "1–2 seconds", isCorrect: false },
      { label: "B", text: "6–9 seconds", isCorrect: true },
      { label: "C", text: "20–30 seconds", isCorrect: false },
    ],
  },

  // ─── WEIGHT & BALANCE (batch 2) ───────────────────────────────────────────
  {
    sourceRef: "wb-useful-load-definition",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "Useful load of an aircraft is defined as the difference between:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Maximum gross weight and basic empty weight", isCorrect: true },
      { label: "B", text: "Maximum gross weight and zero fuel weight", isCorrect: false },
      { label: "C", text: "Gross weight and payload weight", isCorrect: false },
    ],
  },
  {
    sourceRef: "wb-shifting-weight",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "If weight is shifted from the aft baggage compartment to the forward cabin, the CG will:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Move forward", isCorrect: true },
      { label: "B", text: "Move aft", isCorrect: false },
      { label: "C", text: "Remain unchanged because total weight didn't change", isCorrect: false },
    ],
  },
  {
    sourceRef: "wb-overloaded-effect",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "An overloaded aircraft (exceeding maximum gross weight) will experience all of the following EXCEPT:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Higher stall speed", isCorrect: false },
      { label: "B", text: "Longer takeoff run", isCorrect: false },
      { label: "C", text: "Improved climb performance due to increased thrust-to-weight ratio", isCorrect: true },
    ],
  },
  {
    sourceRef: "wb-arm-definition",
    chapterSlug: "weight-and-balance",
    chapterTitle: "Weight and Balance",
    chapterOrder: 8,
    chapterDescription: "Computing CG, loading limits, and effects on performance.",
    stem: "In weight and balance calculations, the 'arm' is defined as:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The weight of an item times its distance from the datum", isCorrect: false },
      { label: "B", text: "The horizontal distance from the datum to the item's location", isCorrect: true },
      { label: "C", text: "The vertical distance from the wing to the ground", isCorrect: false },
    ],
  },

  // ─── PERFORMANCE (batch 2) ────────────────────────────────────────────────
  {
    sourceRef: "perf-service-ceiling",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "Service ceiling is the altitude at which a normally aspirated aircraft can maintain a maximum climb rate of:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "0 fpm (absolute ceiling)", isCorrect: false },
      { label: "B", text: "100 fpm", isCorrect: true },
      { label: "C", text: "500 fpm", isCorrect: false },
    ],
  },
  {
    sourceRef: "perf-runway-slope-effect",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "An upsloping runway will:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Decrease takeoff distance and increase landing distance", isCorrect: false },
      { label: "B", text: "Increase takeoff distance and decrease landing distance", isCorrect: true },
      { label: "C", text: "Have no effect on takeoff or landing distance", isCorrect: false },
    ],
  },
  {
    sourceRef: "perf-wet-grass-effect",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "Compared to a paved dry runway, a soft or wet grass surface will:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Decrease takeoff distance due to additional wheel friction acting as braking", isCorrect: false },
      { label: "B", text: "Increase takeoff distance due to increased rolling resistance", isCorrect: true },
      { label: "C", text: "Have no significant effect on light aircraft performance", isCorrect: false },
    ],
  },
  {
    sourceRef: "perf-cruise-range-vs-endurance",
    chapterSlug: "performance",
    chapterTitle: "Performance",
    chapterOrder: 9,
    chapterDescription: "Takeoff, landing, climb performance, and density altitude.",
    stem: "Maximum range speed differs from maximum endurance speed in that:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Maximum range speed is lower and maximizes time aloft", isCorrect: false },
      { label: "B", text: "Maximum range speed is higher and gives the greatest distance per unit of fuel", isCorrect: true },
      { label: "C", text: "Both speeds are identical for most aircraft", isCorrect: false },
    ],
  },

  // ─── EMERGENCY PROCEDURES (batch 2) ──────────────────────────────────────
  {
    sourceRef: "emerg-vfr-into-imc",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "A VFR pilot who inadvertently enters instrument meteorological conditions (IMC) should immediately:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "Continue at the same altitude and call ATC for help", isCorrect: false },
      { label: "B", text: "Make a 180° turn using gentle bank to return to VFR conditions", isCorrect: true },
      { label: "C", text: "Climb above the clouds and proceed to destination", isCorrect: false },
    ],
  },
  {
    sourceRef: "emerg-lost-communication-vfr",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "A VFR pilot who loses two-way radio communication in Class D airspace should:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "Leave the area immediately and land at the nearest uncontrolled airport", isCorrect: false },
      { label: "B", text: "Squawk 7600 and watch for light gun signals from the tower", isCorrect: true },
      { label: "C", text: "Squawk 7700 and climb above the Class D airspace", isCorrect: false },
    ],
  },
  {
    sourceRef: "emerg-fuel-exhaustion-vs-starvation",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "Fuel starvation (as distinguished from fuel exhaustion) means:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "The aircraft has completely run out of fuel in all tanks", isCorrect: false },
      { label: "B", text: "The engine is not receiving fuel even though fuel is available in the tanks", isCorrect: true },
      { label: "C", text: "The fuel is contaminated with water and cannot be used", isCorrect: false },
    ],
  },
  {
    sourceRef: "emerg-spin-entry",
    chapterSlug: "emergency-procedures",
    chapterTitle: "Emergency Procedures",
    chapterOrder: 10,
    chapterDescription: "Engine failures, forced landings, fires, and emergency equipment.",
    stem: "For a spin to occur, the aircraft must simultaneously experience:",
    acsCode: "PA.IX.A",
    options: [
      { label: "A", text: "A stall and a yaw", isCorrect: true },
      { label: "B", text: "A bank angle greater than 45° and high airspeed", isCorrect: false },
      { label: "C", text: "A power-on condition and low airspeed", isCorrect: false },
    ],
  },

  // ─── PREFLIGHT PLANNING (batch 2) ────────────────────────────────────────
  {
    sourceRef: "preflight-awos-asos",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "AWOS (Automated Weather Observing System) differs from a standard human weather observation in that it:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "Is only available at major airports", isCorrect: false },
      { label: "B", text: "Provides automated, real-time observations but may not detect all weather phenomena", isCorrect: true },
      { label: "C", text: "Is updated manually every 30 minutes by FAA technicians", isCorrect: false },
    ],
  },
  {
    sourceRef: "preflight-closing-flight-plan",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "A VFR flight plan is closed by:",
    acsCode: "PA.I.B",
    options: [
      { label: "A", text: "Landing at the destination — it closes automatically", isCorrect: false },
      { label: "B", text: "The pilot contacting the FSS or tower to close it after landing", isCorrect: true },
      { label: "C", text: "ATC closing it automatically when radar contact is lost", isCorrect: false },
    ],
  },
  {
    sourceRef: "preflight-airmet-tango",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "AIRMET Tango is issued to warn of:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "IFR conditions and mountain obscuration", isCorrect: false },
      { label: "B", text: "Moderate icing", isCorrect: false },
      { label: "C", text: "Moderate turbulence, strong surface winds, and low-level wind shear", isCorrect: true },
    ],
  },
  {
    sourceRef: "preflight-density-altitude-preflight",
    chapterSlug: "preflight-planning",
    chapterTitle: "Preflight Planning",
    chapterOrder: 11,
    chapterDescription: "Weather briefings, NOTAMs, flight plans, and cross-country planning.",
    stem: "Before flight, a pilot computes density altitude primarily to determine:",
    acsCode: "PA.I.C",
    options: [
      { label: "A", text: "The ATC-assigned altitude for cruise", isCorrect: false },
      { label: "B", text: "The aircraft's expected performance during takeoff, climb, and landing", isCorrect: true },
      { label: "C", text: "The correct altimeter setting to use en route", isCorrect: false },
    ],
  },

  // ─── NIGHT OPERATIONS (batch 2) ───────────────────────────────────────────
  {
    sourceRef: "night-dark-adaptation-time",
    chapterSlug: "night-operations",
    chapterTitle: "Night Operations",
    chapterOrder: 12,
    chapterDescription: "Night vision, lighting requirements, and special considerations.",
    stem: "The eyes require approximately how long to fully adapt to darkness after exposure to bright light?",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "5 minutes", isCorrect: false },
      { label: "B", text: "30 minutes", isCorrect: true },
      { label: "C", text: "2 hours", isCorrect: false },
    ],
  },
  {
    sourceRef: "night-off-center-viewing",
    chapterSlug: "night-operations",
    chapterTitle: "Night Operations",
    chapterOrder: 12,
    chapterDescription: "Night vision, lighting requirements, and special considerations.",
    stem: "At night, objects are best seen by using off-center vision because:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "The center of the retina (fovea) is most sensitive to dim light", isCorrect: false },
      { label: "B", text: "The rods, which are located away from the center of the retina, are more sensitive in dim light", isCorrect: true },
      { label: "C", text: "Off-center vision reduces glare from instrument lights", isCorrect: false },
    ],
  },
  {
    sourceRef: "night-spatial-disorientation",
    chapterSlug: "night-operations",
    chapterTitle: "Night Operations",
    chapterOrder: 12,
    chapterDescription: "Night vision, lighting requirements, and special considerations.",
    stem: "Spatial disorientation at night is most effectively prevented by:",
    acsCode: "PA.I.F",
    options: [
      { label: "A", text: "Looking outside frequently for a natural horizon reference", isCorrect: false },
      { label: "B", text: "Trusting your physical sensations to determine aircraft attitude", isCorrect: false },
      { label: "C", text: "Relying on flight instruments rather than visual or physical sensations", isCorrect: true },
    ],
  },
  {
    sourceRef: "night-anticollision-lights",
    chapterSlug: "night-operations",
    chapterTitle: "Night Operations",
    chapterOrder: 12,
    chapterDescription: "Night vision, lighting requirements, and special considerations.",
    stem: "Anti-collision lights (strobe lights or rotating beacon) are required to be on:",
    acsCode: "PA.I.D",
    options: [
      { label: "A", text: "Only during night flight", isCorrect: false },
      { label: "B", text: "Any time the aircraft is in flight, day or night", isCorrect: true },
      { label: "C", text: "Only when operating within 10 miles of an airport", isCorrect: false },
    ],
  },
];
